points = {
    "Donald Trump" : 10,
    "ma sucette" : 5,
    "de la confiture" : 5,
    "le dernier mètre" : 10,
    "le Far-west" : 5,
    "faire l'hélicoptère devant sa mère" : 20,
    "Maitre Gims" : 25,
    "recoucher avec son ex" : 10,
    "l'haleine du prof de maths" : 25,
    "un kebab de pangolin" : 30,
    "ouvrir un compte en Suisse" : 25,
    "mon ex" : 30,
    "Jean-Yves le Drian" : 20,
    "l'oeil de verre de Jean Marie le Pen" : 25,
    "le crocher du capitaine" : 15,
    "un camembert bien coulant" : 30,
    "Brontis" : 35,
    "une pièce, une cigarette ou un ticket restaurant" : 30,
    "un long bain de minuit" : 25,
    "Ebola" : 10,
    "une mutation à Auxerre" : 20,
    "l'hygiène bucco-dentaire" : 20,
    "pisser face au vent" : 30,
    "la tribu de Dana" : 25,
    "1.5L de coca" : 15,
    "une odeur pas fraîche" : 15,
    "nos ancêtres les Gaulois" : 20,
    "un cours d'aqua-poney" : 15,
    "la messe du dimanche" : 20,
    "mon kiné" : 20,
    "une coloscopie": 15,
    "un cactus dans le salon" : 15,
    "laisser ses chaussettes sécher à la fenêtre" : 20,
    "le chien de la voisine" : 25,
    "une partouze masquée avec François Hollande" : 10,
    "Pierre ménès qui a la gastro" : 15,
    "des dreads sous les aisselles" : 10,
    "regarder Games of Thrones" : 15,
    "les aventures de Winnie l'Ourson" : 25,
    "compter jusqu'à 3 avec Franklin" : 20,
    "souffler dans la chicha" : 15,
    "les fantômes" : 15,
    "tirer la chasse d'eau" : 10,
    "Bernard Tapis" : 15,
    "HETIC" : 35,
}