


points = {
    "Hitler" : 10,
    "ma bite" : 5,
    "20cm de bonheur" : 15,
    "les derniers centimetres" : 10,
    "un autiste" : 10,
    "faire l'helicoptère devant sa mere" : 20,
    "Maitre Gims" : 25,
    "une vegan qui se demande si elle peut avaler" : 15,
    "recoucher avec son ex" : 10,
    "jouir en 30s et s'en taper" : 10,
    "l'haleine du prof de maths" : 25,
    "une sodomie surprise" : 10,
    "traire une femme qui allaite" : 20,
    "des testicules trop pleines" : 10,
    "un kebab de pangolin" : 30,
    "ouvrir un compte en Suisse" : 25,
    "un cancer de la prostate" : 10,
    "mon ex" : 30,
    "300 matelots en rut après 6 mois en haute mer" : 20,
    "Jean-Yves le Drian" : 20,
    "l'oeil de verre de Jean Marie le Pen" : 25,
    "un camembert bien coulant" : 30,
    "Brontis" : 35,
    "une pièce, une cigarette ou un ticket restaurant" : 30,
    "la coulante" : 15,
    "les longues caresses de papy" : 15,
    "un long bain de minuit" : 25,
    "la sortie d'ecole" : 15,
    "Ebola" : 10,
    "une mutation à Auxerre" : 20,
    "l'hygiene bucco-dentaire" : 20,
    "pisser face au vent" : 30,
    "la tribu de Dana" : 25,
    "1.5L de coca" : 15,
    "une odeur de moule" : 15,
    "les vegans" : 15,
    "nos ancetres les Gaulois" : 20,
    "un cours d'aqua-poney" : 15,
    "un pretre" : 15,
    "la messe du dimanche" : 20,
    "une sonde anale" : 15,
    "mon kine" : 20,
    "un cactus dans le salon" : 15,
    "laisser ses chaussettes secher à la fenetre" : 20,
    "un repas de famille avec ton oncle raciste" : 15,
    "le coming-out de mon frere" : 25,
    "le chien de la voisine" : 25,
    "les Roms" : 15,
    "une partouze masquee avec François Hollande" : 10,
    "Pierre Menes que a la gastro" : 15,
    "des dreads sous les aisselles" : 10,
    "jouer à cache-cache contre Nordhal Lelandais" : 20,
    "regarder Games of Thrones" : 15,
    "les aventures de Winnie l'Ourson" : 25,
    "compter jusqu'à 3 avec Franklin" : 20,
    "souffler dans la chicha" : 15,
    "les fantomes" : 15,
    "tirer la chasse d'eau" : 10,
    "Bernard Tapis" : 15,
    "HETIC" : 35,
}

# Cat 1 Sujet
Mcat1 = ["une odeur de moule",
         "les vegans",
         "nos ancetres les gaulois",
         "un cours d’aqua-poney",
         "un pretre",
         "la messe du dimanche",
         "les derniers centimetres",
         "Maitre Gims",
         "l'haleine du prof de maths",
         "un kebab de pangolin",
         "mon ex",
         "300 matelots en rut après 6 mois en haute mer",
         "Jean-Yves le Drian",
         "l'oeil de verre de Jean Marie le Pen",
         "un camembert bien coulant",
         "Brontis",
         "une piece, une cigarette ou un ticket restaurant",
         "un long bain de minuit",
         "la sortie d'ecole",
         "Ebola",
         "une mutation à Auxerre",
         "l'hygiene bucco-dentaire",
         "la tribu de Dana",
         "1.5L de coca",
         "une odeur de moule",
         "un cours d'aqua-poney",
         "mon kine",
         "un cactus dans le salon",
         "le coming-out de mon frere",
         "le chien de la voisine",
         "les Roms",
         "Pierre Menes que a la gastro",
         "des dreads sous les aisselles",
         "les aventures de Winnie l'Ourson",
         "les fantômes",
         "Bernard Tapis",
         "HETIC"]


# Cat 2 : COD/COI
Mcat2 = ["jouer à cache-cache contre Nordhal Lelandais",
"faire l'helicoptere devant sa mere",
"regarder Games of Thrones",
"tirer la chasse d'eau",
"recoucher avec son ex",
"jouir en 30s et s'en taper",
"laisser ses chaussettes secher à la fenetre",
"traire une femme qui allaite",
"souffler dans la chicha",
"pisser face au vent",
"compter jusqu'à 3 avec Franklin",
"ouvrir un compte en Suisse"]

# Cat 3 : passe partout mechant
Mcat3 = ["Hitler",
"ma bite",
"20 cm de bonheur",
"un autiste",
"une vegan qui se demande si elle peut avaler",
"une partouze masquee avec François Hollande",
"une sodomie surprise",
"des testicules trop pleines",
"une sonde anale",
"un cancer de la prostate",
"les longues caresses de papy",
"la coulante",
"un repas de famille avec ton oncle raciste"]

###################

# Catégories phrases :

# Cat 1 : Sujet
Pcat1 = [format("{} c’est une bonne personne mais pas du tout"),
format("{} me scotch aux lunettes de toilette"),
format("Scandale à Roubaix un professeur montre {} à ses eleves"),
format("je bois pour oublier {}"),
format("Regarder {} permet de me calmer"),
format("L’Egypte a les pyramides et la France {}"),
format("Ma meilleure amie m’a avouee qu’elle kiffait {}"),
format("Juda trahit Jesus lorsqu’il a decouvert {}"),
format("Nouvelle emission de telerealite les ch'tis et {}"),
format("{} C’est tout ce que je demande"),
format("{}, ça fond dans la bouche, pas dans la main"),
format("{}, c'est encore meilleur la 2eme fois"),
format("Le 7ème jour Dieu crea {}"),
format("{} ça a l'air marrant, mais en fait ça fait mal")]

# Cat 2 : COD
Pcat2= [format("{} le meilleur livre pour la fete des peres"),
format("{} le meilleur livre pour la fête des meres"),
format("{} me scotch aux lunettes de toilette"),
format("{} m’a appris le sens de la vie "),
format("{}, c'est encore meilleur la 2eme fois"),
format("{} ça a l'air marrant, mais en fait ça fait mal"),
format("{}, rien de mieux pour briser la glace"),
format("{} C’est tout ce que je demande")]

# Cat 3 : TOUT
Pcat3 = [format("Quand j’etais petit, les autres voulaient etre pompier, moi ce que je voulais c’est {}"),
format("{} c’est triste mais drole en même temps"),
format("{} bon de la premiere cuillere jusqu’à la derniere goutte"),
format("demande à ton medecin si {} est bon pour toi"),
format("Le cadeau parfait pour une femme qui a dejà tout {}"),
format("Rater la naissance de son fils pour {} à la rigueur ça peut se comprendre"),
format("Didier Raoult a invente {} contre le coronavirus"),
format("{} c’est comme une bonne guerre, ça forge la jeunesse"),
format("Bon vent et gare à toi {} est si vite arrivee"),
format("pour me faire pardonner je te propose {}"),
format("{} pour les nuls, le livre ideal pour la fête de meres"),
format("{} me donne des gaz incontrolables"),
format("Mon petit dejeuner prefere, c'est {}"),
format("{} La plus grande difference entre les hommes et les femmes"),
format("{} c'est tellement ton pere !"),
format("entre {} et une vie de famille, il faut choisir")]


