# We use he format method for each sentences because it allows us to set  where the selected word will be added
sentences = [format("{} c’est une bonne personne mais pas du tout"),
             format("demande à ton médecin si {} est bon pour toi"),
             format("je bois pour oublier {}"),
             format("Regarder {} permet de me calmer"),
             format("Le cadeau parfait pour une femme qui a déjà tout {}"),
             format("L’Egypte a les pyramides et la France {}"),
             format("Didier Raoult a inventé {} contre le coronavirus"),
             format("{}, ça fond dans la bouche, pas dans la main"),
             format("{}, c'est encore meilleur la 2ème fois"),
             format("Mon petit déjeuner préféré, c'est {}"),
             format("Le 7ème jour Dieu créa {}"),
             format("{} me donne des gaz incontrôlables"),
             format("{} pour les nuls, le livre idéal pour la fête de mères"),
             format("{} ça a l'air marrant, mais en fait ça fait mal"),
             format("entre {} et une vie de famille, il faut choisir"),
             format("{} c'est tellement ton père !"),
             format("pour me faire pardonner je te propose {}"),
             format("{} La plus grande différence entre les hommes et les femmes"),
             format("{}, rien de mieux pour briser la glace"),
             format("{} C’est tout ce que je demande"),
             format("{} challenge accepted"),
             format("Bon vent et gare à toi {} est si vite arrivée"),
             format("{} c’est comme une bonne guerre, ça forge la jeunesse"),
             format("Râté la naissance de son fils pour {} à la rigueur ça peut se comprendre"),
             format("Nouvelle émission de téléréalité les ch'tis et {}"),
             format("Juda trahit Jésus lorsqu’il a découvert {}"),
             format("Ma meilleure amie m’a avouée qu’elle kiffait {}"),
             format("Quand j’étais petit, les autres voulaient être pompier, moi ce que je voulais c’est {}"),
             format("{} C’est encore meilleur la 2ème fois "),
             format("Après 20 ans de débat, l’assemblée a enfin voté que {}"),
             format("Scandale à Roubaix un professeur montre {} à ses élèves"),
             format("{} m’a appris le sens de la vie "),
             format("{} me scotch aux lunettes de toilette"),
             format("{} le meilleur livre pour la fête des pères"),
             format("{} le meilleur livre pour la fête des mères"),
             format("{} bon de la première cuillère jusqu’à la dernière goutte"),
             format("{} c’est triste mais drôle en même temps"),
]
