words = [
    "les vegans",
    "nos ancêtres les gaulois",
    "un cours d'aqua-poney",
    "la messe du dimanche",
    "Maitre Gims",
    "une vegan qui se demande \n si elle peut avaler",
    "redormir avec son ex",
    "sortir la sauce en 30s et s'en taper",
    "l'haleine du prof de maths",
    "un kebab de pangolin",
    "ouvrir un compte en Suisse",
    "un cancer de la prostate",
    "mon ex",
    "Jean-Yves le Drian",
    "l'oeil de verre de \n Jean Marie le Pen",
    "un camembert bien coulant",
    "Brontis",
    "la coulante",
    "les caresses de papy",
    "un bain de minuit",
    "la sortie d'école",
    "Ebola",
    "une mutation à Auxerre",
    "l'hygiène bucco-dentaire",
    "pisser face au vent",
    "la tribu de Dana",
    "1.5L de coca",
    "une odeur de moule",
    "une sonde",
    "mon kiné",
    "un cactus dans le salon",
    "laisser ses chaussettes \n sécher à la fenêtre",
    "un repas de famille avec \nton oncle raciste",
    "le coming-out de mon frère",
    "le chien de la voisine",
    "les Roms",
    "une soirée masquée avec \n François Hollande",
    "Pierre ménès qui a la gastro",
    "des dreads sous les aisselles",
    "jouer à cache-cache",
    "Nordhal Lelandais",
    "regarder Games of Thrones",
    "les aventures de Winnie l'Ourson",
    "compter jusqu'à 3 avec Franklin",
    "souffler dans la chicha",
    "les fantômes",
    "tirer la chasse d'eau",
    "Bernard Tapis",
    "HETIC",
    "Sans les mains"
]
